### ISSUE TITLE
Add common useful Jupyter extensions

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-kernels#100]
First, we need to install the extension configurator from https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html,
and then enable specific extensions in the Dockerfiles.

Users will be able to install additional extensions in running containers via the configurator, but currently they are volatile; i.e., users have to reinstall them when spawning new compute sessions.

**Comment by inureyes** [comment]
NextG / FF kernels covers this issue. b0fdddeed72cbacaeeb
