### ISSUE TITLE
Cannot run python snippet on client

### ISSUE THREAD

**Issue by Nozomeister** [lablup/backend.ai-kernels#101]
Dear Backend.AI team,
I have followed the development setup here: https://docs.backend.ai/en/latest/install/development-setup.html and get the backend.ai managers and server running.
While testing the python command-line execution, it showed up with the error:
✘ [0] BackendAPIError(400, 'Bad Request', {'type': 'https://api.backend.ai/probs/invalid-api-params', 'title': 'Missing or invalid API parameters. (Unknown image reference: python)'})

Can you help me with this? I have tried to pull the python3.6 kernel again, but there is no change.
Best regards.

**Comment by adrysn** [comment]
Does it happen to solve the problem when changing `python` to `python:3.6-ubuntu18.04` like below?

```backend.ai run python:3.6-ubuntu18.04 -c 'print("hello")'```

**Comment by Nozomeister** [comment]
Thanks for the response. When I change the code to that command, it responded with:
✘ [0] BackendAPIError(500, 'Internal Server Error', {'type': 'https://api.backend.ai/probs/internal-server-error', 'title': 'Internal server error.'})
which I think happened because I am using Ubuntu 16.04
If I change to 16.04, it will produce the same error as the first error I encountered.

**Comment by adrysn** [comment]
I made a hotfix for the problem I mentioned. https://github.com/lablup/backend.ai-manager/commit/0586e22237fc8672826800b57f774460b99d8671

Instead of doing alembic downgrade and checking out to previous commits, try this after git pull and then execute the code:
```
alembic upgrade head
```

**Comment by adrysn** [comment]
I'll close this issue since there is no further comments.
