### ISSUE TITLE
Julia Support

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-kernels#11]
- [x] Basic REPL implementation
- [x] Pre-install a list of essential packages

**Comment by achimnol** [comment]
Let's add TensorFlow flavor of Julia.
https://github.com/malmaud/TensorFlow.jl/tree/master/src

**Comment by achimnol** [comment]
Currently Julia kernel has some race-condition-like issues:
 * Running a code snippet may or may not return its result immediately. Sometimes it requires multiple times of repeated queries to get results. (The result itself looks sane.)
 * When importing PyPlot, above problem arises almost always.

**Comment by bluehope** [comment]
Julia 0.5.2 released! 
[https://github.com/JuliaLang/julia/releases/download/v0.5.2/julia-0.5.2.tar.gz](https://github.com/JuliaLang/julia/releases/download/v0.5.2/julia-0.5.2.tar.gz)
