### ISSUE TITLE
Upgrade base TensorFlow / pytorch kernel to use Python 3.8

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-kernels#140]
* Upgrade base TensorFlow / pytorch kernel to use Python 3.8
 * Currently it is using python 3.6.

**Comment by hephaex** [comment]
Upgrade base TensorFlow to use Python 3.8 : python-tensorflow:2.4-py38-cuda11.1
Upgrade base Pytorch to use Python 3.8 :  python-pytorch:1.7-py38-cuda11.1
