### ISSUE TITLE
Haskell support

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-kernels#18]
- Haskell support
- For language specific course.

**Comment by adrysn** [comment]
Handling Monad is too confusing for me. I haven't figured out how to walk about among various monads yet, and this prevents me to write execution routine and intercepting std*.

Instead, I will try to write a haskell code execution script with other languages (e.g. python):
* ZMQ / std* handling is done by a python script.
* User's haskell code will be saved as a temporary file (e.g.: tmp_haskell.hs)
* The saved code will be executed by running `runhaskell tmp_haskell.hs`.
* The temporary file will be deleted.
* Captured execution result will be parsed and returned in a python script.
