### ISSUE TITLE
Update python3 related kernel to python 3.6

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-kernels#33]
* Update python3 related kernel to python 3.6

**Comment by achimnol** [comment]
Current status: All done except python3-caffe kernel.

**Comment by inureyes** [comment]
:+1:

2017. 2. 25. 10:42 Joongi Kim <notifications@github.com<mailto:notifications@github.com>> 작성:


Current status: All done except python3-caffe kernel.

**Comment by achimnol** [comment]
Caffe "seems" to be working with Python 3.6. minideb:jessie provides libboost_python libraries for Python 3.4 only – currently I just symlinked them to be generic Python 3.x library files but this may break something. It would be best to compile libboost by ourselves.

All other Python3 kernels are now upgraded to Python 3.6.2.
