### ISSUE TITLE
Enhance TensorFlow support

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-kernels#40]
* [x] [TensorBoard](https://www.tensorflow.org/get_started/summaries_and_tensorboard) – replaced by lablup/cloud.backend.ai#38 (internal issue)
 * ~~[ ] [TensorFlow Fold](https://github.com/tensorflow/fold~~ → Not maintained.
 * [x] https://github.com/microsoft/tensorwatch
 * more?

**Comment by inureyes** [comment]
TensorBoard would be a killer feature (for TensorFlow users)!
