### ISSUE TITLE
Add pyproj and cartopy support to Python kernels

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-kernels#71]
They are used to plot geographic data.

**Comment by hephaex** [comment]
commit #fad06 :  Alpine3.6 kernel support pylori and carroty

**Comment by hephaex** [comment]
when ubuntu build up, kernel occurred "E: Unable to locate package proj-dev".
it may be fixed "apt-get libproj-dev" add on python build sequence.

**Comment by hephaex** [comment]
commit b2c973, pyproj & cartopy support ubuntu python kernels
