### ISSUE TITLE
Ubuntu 18.04 LTS support

### ISSUE THREAD

**Issue by hephaex** [lablup/backend.ai-kernels#75]
Ubuntu 18.04 LTS released, 
we need to support  both kernel 16.04 and 18.04

**Comment by achimnol** [comment]
Just a note: When running Docker containers in Ubuntu 18.04, we need to configure DNS resolver addresses manually in `/etc/docker/daemon.json` since Ubuntu 18.04 uses a locally cached DNS daemon located at `127.0.0.53` which is not accessible from containers.
