### ISSUE TITLE
use MPI-enabled TensorFlow r1.9

### ISSUE THREAD

**Issue by hephaex** [lablup/backend.ai-kernels#82]
By using MPI protocol TensorFlow can take advantage of the high performance networking primitives.
The MPI API enables TensorFlow to take advantage of high performance low latency networks.

step1. setup openMPI pacage on common kernel
step2. configure TF_NEED_MPI=1 

reference. tensorflow/tensorflow/contrib/mpi/

**Comment by inureyes** [comment]
@hephaex please check this out. 👍

**Comment by inureyes** [comment]
@hephaex  please confirm this issue.
