### ISSUE TITLE
Make client accept humanized memory resource unit

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-kernels#91]
Currently, the memory unit is GB: `0.5 == 512 MiB`, `1 == 1024MiB`. Let use can deliver humanized unit. For example, `-r ram=512mb`, `-r ram=2.5GB`.

**Comment by achimnol** [comment]
I think this issue should be moved to [backend.ai-client-py repository........](https://github.com/lablup/backend.ai-client-py)

**Comment by adrysn** [comment]
Why am I make this here? -_-...

**Comment by adrysn** [comment]
Closing this mis-placed issue by referring https://github.com/lablup/backend.ai-client-py/issues/32.
