### ISSUE TITLE
Tensorflow kernel run

### ISSUE THREAD

**Issue by hong-sh** [lablup/backend.ai-kernels#94]
안녕하세요 진행중인 과제에 backend.ai를 활용하기 위해 이것저것 테스트해보고 있습니다.
Virtualbox에 ubuntu를 설치하여 backend.ai를 구동 시킨 뒤 host PC인 Window에서 Jupyter integration을 통해 python 3.6 kernel까지 실행해보았습니다.
다음으로 tensorflow kernel을 실행해보고자 docker pull을 통해 tensorflow latest 버전을 가져와 실행해보았는데 backend.ai.KernelNotfoundError가 발생하고있습니다.  kernel을 따로 실행시켜주는 cmd line이 있는건가요? docker 개념이 생소하여 질문드립니다.
ps. python 3.6 버전에서 종종 session이 죽지않고 503 service not available error도 발생하여 backend.ai kill을 통해 강제 종료 시킨 뒤 사용하고 있는데 이 부분도 궁금합니다.

**Comment by achimnol** [comment]
안녕하세요!

1. `KernelNotFound` 에러가 나는 경우는 docker image가 실제로 agent에 존재하더라도 manager 쪽에서 해당 이미지에 대한 metadata를 가지고 있지 않은 경우 발생합니다. 저희가 최근 이미지 관리 방식에 좀 변화를 주고 있어서 설치 방법에 따라 metadata가 미처 등록되지 않은 경우일 것 갈습니다.
사용하신 설치 방법과 pull로 가져오신 tensorflow 이미지의 정확한 태그명을 알려주시면 감사하겠습니다.

2. VirtualBox를 사용 중이시기 때문에, 가상머시에 할당된 메모리 용량이나 코어 수에 따라 Python 세션이 이미 실행 중인 경우 새로운 세션이 자원부족으로 판단되어 뜨지 않을 수 있습니다.
   * `backend.ai run` 또는 `backend.ai start` 명령을 실행하실 때 `-r` 옵션으로 자원을 할당할 수 있는데 이것을 줄여보시거나, 기본값으로 할당되는 자원량을 metadata를 통해 줄여서 더 여러 개가 뜨도록 할 수 있습니다. 가상머신에 할당되어 있는 코어 수와 메모리 용량을 알려주시면 설정방법을 안내해드리겠습니다.
   * 또는, 기존 세션을 계속 유지하면서 그 세션 안에서 새로운 코드를 이어서 실행하려고 하는 경우라면, `backend.ai ps` 명령으로 세션 ID를 확인하신 후 `backend.ai run -t <sessionid> ...`와 같이 해당 세션에서 코드를 실행하도록 지정하는 방법이 있습니다.

**Comment by inureyes** [comment]
@achimnol Can I close this issue?
